#!/bin/sh
################################################################################

### Resolve o bug, de não carregaga os arquivos de configuração da pasta
### /etc/triggerhappy/triggers.d necessário para ativar os atalhos de teclado.

/etc/init.d/K10triggerhappy start

################################################################################

matchbox-window-manager -use_cursor no -use_titlebar no -use_desktop_mode no -use_lowlight no &

# set the keyboard
systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.py"
settings_lang="`$systemsetting -command load -key system.language`"

# not always true (en_US for us), but it's really better than always english
map_name=$(echo $settings_lang | cut -c 1-2)
setxkbmap "${map_name}"

# disable dpms to prevent screen from blanking
xset -dpms
xset s off

export HOME=/userdata/system
export LC_ALL="${settings_lang}.UTF-8"
export LANG=${LC_ALL}

# because of xinerama braking es, enable only one screen at a time
systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.py"
settings_output="`$systemsetting -command load -key global.videooutput`"
batocera-resolution setOutput "${settings_output}" # empty or invalid values defaults to the first valid
#/recalbox/scripts/recalbox-config.sh setoutput "${settings_output}"
#/recalbox/scripts/recalbox-config.sh setoutput 'HDMI-1'

batocera-resolution minTomaxResolution

################################################################################

## CUSTOMISATIONS ###
# to customize your display, you can copy this file to ~/.xinitrc and then modify it

# rotate the screen
# xrandr -o left
# xrandr -o right
# xrandr -o inverted

### Resolution VGA 4x3
#xrandr -r 60 -s 160x120
#xrandr -r 60 -s 360x640
#xrandr -r 60 -s 640x480
#xrandr -r 60 -s 720x480
#xrandr -r 60 -s 800x600
#xrandr -r 60 -s 1024x768

### ResolutionHD 16x9
#xrandr -r 60 -s 1280x720
#xrandr -r 60 -s 1920x1080

### Resolution OUTRAS 16x9
#xrandr -r 60 -s 1152x864
#xrandr -r 60 -s 1280x800
#xrandr -r 60 -s 1440x900
#xrandr -r 60 -s 1600x900

################################################################################

### Usa a resolução especificada no arquivo /boot/recalbox-boot.conf

if [ "$(cat /boot/recalbox-boot.conf | grep ^resolution)" ]; then
    xRes="$(cat /boot/recalbox-boot.conf | grep ^resolution | cut -d '=' -f 2 | cut -d 'x' -f 1)"
    yRes="$(cat /boot/recalbox-boot.conf | grep ^resolution | cut -d '=' -f 2 | cut -d 'x' -f 2)"
    Freq="$(cat /boot/recalbox-boot.conf | grep ^resolution | cut -d '=' -f 2 | cut -d 'x' -f 3)"
    xrandr -r $Freq -s "$(echo $xRes)x$(echo $yRes)"
fi

################################################################################

### Força o vsync

xset -dpms
xset s off

################################################################################

### Resolve o bug de não identificar o teclado PT-BR ABNT2

if [ "$(cat $HOME/recalbox.conf | grep system.language=pt_BR)" ]; then
    setxkbmap -model abnt2 -layout br -variant ,abnt2 &
fi

################################################################################

### Imagem de carregamento alternativa.

if [ -f "$HOME/.emulationstation/es_settings.cfg" ]; then
    THEME_NAME="$(cat "$HOME/.emulationstation/es_settings.cfg" | grep '<string name="ThemeSet" value=' | cut -d '"' -f 4)"
    if ! [ "$THEME_NAME" ]; then
        THEME_NAME='batocera-plus'
    fi
else
    THEME_NAME='batocera-plus'
fi

if [ -d "$HOME/.emulationstation/themes/$THEME_NAME" ]; then
    THEME_DIR="$HOME/.emulationstation/themes/$THEME_NAME"
elif [ -d "/usr/share/batocera/datainit/system/.emulationstation/themes/$THEME_NAME" ]; then
    THEME_DIR="/usr/share/batocera/datainit/system/.emulationstation/themes/$THEME_NAME"
else
    THEME_DIR='/usr/share/batocera/datainit/system/.emulationstation/themes/batocera-plus'
fi

if [ -f "$THEME_DIR/loadscreen/startscreen.png" ]; then
    START_SCREEN="$THEME_DIR/loadscreen/startscreen.png"
elif [ -f "$THEME_DIR/loadscreen/startscreen.jpg" ]; then
    START_SCREEN="$THEME_DIR/loadscreen/startscreen.jpg"
else
    START_SCREEN='/usr/share/batocera/datainit/system/.emulationstation/themes/batocera-plus/loadscreen/startscreen.png'
fi

while [ true ]; do
    # Aguarda o emulationstation entrar em execução para executar o retroarch.
    if [ "$(pidof emulationstation)" ]; then
        nice -n -1 /usr/bin/retroarch -L '/usr/lib/libretro/imageviewer_libretro.so' --config '/usr/share/batocera/datainit/system/configs/retroarch/retroarchcustom.cfg' \
        "$START_SCREEN" &
        break
    fi
done &

################################################################################

### Interrompe a tela de carregamento quando o emulationstation terminar o loading.

while [ true ]; do
    sleep 0.5
    if [ -f '/tmp/emulationstation.ready' ]; then
        killall retroarch

        ### Inicia com o favoritos selecionado
        ### Ex: xSendKey left enter
        sleep 0.2
        xSendKey left

        break
    fi
done &

################################################################################

# without windowed, time must be sleeped to wait that matchbox ended to initialize :-(
exec emulationstation --windowed
